import type { CopyFragment } from "./types";

/**
 * Copy for the invoices area. Each entry: a stable namespaced key, the English
 * default (source of truth), the editor group + a human label. Migration adds
 * entries here; render sites call t("<key>"). Keys MUST be globally unique.
 */
export const invoicesCopy: CopyFragment = [
  /* ---------------- Invoices list (src/app/invoices/page.tsx) ---------------- */
  { key: "invoices.list.eyebrow", default: "Sales", group: "Invoices", label: "List page eyebrow" },
  { key: "invoices.list.title", default: "Invoices", group: "Invoices", label: "List page title" },
  { key: "invoices.list.titleDrafts", default: "Invoices · drafts to review", group: "Invoices", label: "List page title (drafts filter)" },
  { key: "invoices.list.newInvoice", default: "New invoice", group: "Invoices", label: "‘New invoice’ button" },
  { key: "invoices.list.draftBannerFrom", default: "from the delivery login", group: "Invoices", label: "Draft banner: mid text after count", multiline: true },
  { key: "invoices.list.draftBannerIsWaiting", default: " is waiting for review — tap to see ", group: "Invoices", label: "Draft banner: singular waiting suffix", multiline: true },
  { key: "invoices.list.draftBannerAreWaiting", default: " are waiting for review — tap to see ", group: "Invoices", label: "Draft banner: plural waiting suffix", multiline: true },
  { key: "invoices.list.draftBannerIt", default: "it", group: "Invoices", label: "Draft banner: singular ‘it’" },
  { key: "invoices.list.draftBannerThem", default: "them", group: "Invoices", label: "Draft banner: plural ‘them’" },
  { key: "invoices.list.showAll", default: "← Show all invoices", group: "Invoices", label: "‘Show all invoices’ link (drafts filter)" },
  { key: "invoices.list.emptyDrafts", default: "No drafts awaiting review.", group: "Invoices", label: "Empty state: no drafts" },
  { key: "invoices.list.empty", default: "No invoices yet.", group: "Invoices", label: "Empty state: no invoices" },
  { key: "invoices.list.colInvoice", default: "Invoice", group: "Invoices", label: "Table column: Invoice" },
  { key: "invoices.list.colParty", default: "Party", group: "Invoices", label: "Table column: Party" },
  { key: "invoices.list.colDate", default: "Date", group: "Invoices", label: "Table column: Date" },
  { key: "invoices.list.colStatus", default: "Status", group: "Invoices", label: "Table column: Status" },
  { key: "invoices.list.colBalanceDue", default: "Balance due", group: "Invoices", label: "Table column: Balance due" },
  { key: "invoices.list.colTotal", default: "Total", group: "Invoices", label: "Table column: Total" },
  { key: "invoices.list.outstanding", default: "outstanding", group: "Invoices", label: "Footer: outstanding label" },

  /* -------------- New invoice page (src/app/invoices/new/page.tsx) -------------- */
  { key: "invoices.new.backAll", default: "← All invoices", group: "New Invoice", label: "Back link" },
  { key: "invoices.new.eyebrow", default: "Sales", group: "New Invoice", label: "Page eyebrow" },
  { key: "invoices.new.title", default: "New invoice", group: "New Invoice", label: "Page title" },
  { key: "invoices.new.subtitleSimple", default: "Every amount is recomputed on the server through the shared billing engine.", group: "New Invoice", label: "Subtitle (glazing off)", multiline: true },
  { key: "invoices.new.subtitleBills", default: "bills on", group: "New Invoice", label: "Subtitle: ‘bills on’ (before net)" },
  { key: "invoices.new.subtitleNet", default: "net", group: "New Invoice", label: "Subtitle: emphasised ‘net’" },
  { key: "invoices.new.subtitleWeightAfter", default: "weight after", group: "New Invoice", label: "Subtitle: ‘weight after’ (before glazing term)" },
  { key: "invoices.new.subtitleEnterGross", default: "; enter gross + the buyer's final weight and the % is derived.", group: "New Invoice", label: "Subtitle: enter-gross clause", multiline: true },
  { key: "invoices.new.subtitleHasNo", default: "has no", group: "New Invoice", label: "Subtitle: ‘has no’ (before glazing term)" },
  { key: "invoices.new.subtitleEngine", default: ". Every amount is recomputed on the server through the shared billing engine.", group: "New Invoice", label: "Subtitle: billing-engine clause", multiline: true },

  /* ---------- Invoice form (src/app/invoices/new/InvoiceForm.tsx) ---------- */
  { key: "invoices.form.invoicePrefix", default: "Invoice", group: "Invoice Form", label: "Success heading: ‘Invoice’ prefix (before #number)" },
  { key: "invoices.form.sentForReview", default: "sent for review", group: "Invoice Form", label: "Success heading suffix (delivery)" },
  { key: "invoices.form.savedSuffix", default: "saved", group: "Invoice Form", label: "Success heading suffix (office)" },
  { key: "invoices.form.referencePrefix", default: "Reference", group: "Invoice Form", label: "Success body: reference prefix" },
  { key: "invoices.form.totalPrefix", default: "Total", group: "Invoice Form", label: "Success body: total prefix" },
  { key: "invoices.form.successDraft", default: "It is saved as a draft — the office will review and approve it. You can open it to print or add a package photo.", group: "Invoice Form", label: "Success body (delivery draft)", multiline: true },
  { key: "invoices.form.successImmutable", default: "An immutable delivery record was created for dispute defense.", group: "Invoice Form", label: "Success body (office)", multiline: true },
  { key: "invoices.form.openInvoice", default: "Open invoice →", group: "Invoice Form", label: "‘Open invoice’ link" },
  { key: "invoices.form.viewLedger", default: "View party ledger →", group: "Invoice Form", label: "‘View party ledger’ link" },
  { key: "invoices.form.newAnother", default: "New another", group: "Invoice Form", label: "‘New another’ button" },
  { key: "invoices.form.labelParty", default: "Party", group: "Invoice Form", label: "Field label: Party" },
  { key: "invoices.form.selectParty", default: "Select party…", group: "Invoice Form", label: "Party select placeholder option" },
  { key: "invoices.form.labelChannel", default: "Channel", group: "Invoice Form", label: "Field label: Channel" },
  { key: "invoices.form.labelReferenceNumber", default: "Reference number", group: "Invoice Form", label: "Field label: Reference number" },
  { key: "invoices.form.referenceNumberPlaceholder", default: "e.g. SSI-000123", group: "Invoice Form", label: "Reference number input placeholder" },
  { key: "invoices.form.labelDate", default: "Date", group: "Invoice Form", label: "Field label: Date" },
  { key: "invoices.form.labelNotes", default: "Notes", group: "Invoice Form", label: "Field label: Notes" },
  { key: "invoices.form.hintOptional", default: "optional", group: "Invoice Form", label: "Field hint: optional" },
  { key: "invoices.form.notesPlaceholder", default: "Notes (optional)", group: "Invoice Form", label: "Notes input placeholder" },
  { key: "invoices.form.notesPick", default: "Insert a saved note…", group: "Invoice Form", label: "Saved-note picker placeholder" },
  { key: "invoices.form.expensesTitle", default: "Invoice expenses", group: "Invoice Form", label: "Expenses section title" },
  { key: "invoices.form.expensesHint", default: "internal cost — not shown on the invoice", group: "Invoice Form", label: "Expenses section hint" },
  { key: "invoices.form.expensesLabelPlaceholder", default: "e.g. Labour — carrying cartons", group: "Invoice Form", label: "Expense label input placeholder" },
  { key: "invoices.form.expensesAmountPlaceholder", default: "Amount", group: "Invoice Form", label: "Expense amount input placeholder" },
  { key: "invoices.form.expensesRemove", default: "Remove expense", group: "Invoice Form", label: "Remove-expense button aria-label" },
  { key: "invoices.form.expensesAdd", default: "+ Add expense", group: "Invoice Form", label: "Add-expense button" },
  { key: "invoices.form.colItem", default: "Item", group: "Invoice Form", label: "Line table header: Item" },
  { key: "invoices.form.colGross", default: "Gross", group: "Invoice Form", label: "Line table header: Gross (before unit)" },
  { key: "invoices.form.colNetIn", default: "Net", group: "Invoice Form", label: "Line table header: Net (before ‘{unit} in’)" },
  { key: "invoices.form.colRate", default: "Rate", group: "Invoice Form", label: "Line table header: Rate" },
  { key: "invoices.form.colNet", default: "Net", group: "Invoice Form", label: "Line table header: Net (before unit, right col)" },
  { key: "invoices.form.colAmount", default: "Amount", group: "Invoice Form", label: "Line table header: Amount" },
  { key: "invoices.form.selectItem", default: "Select…", group: "Invoice Form", label: "Item select placeholder option" },
  { key: "invoices.form.removeLine", default: "Remove line", group: "Invoice Form", label: "Remove-line button tooltip" },
  { key: "invoices.form.overDeduction", default: "⚠ Over-deduction", group: "Invoice Form", label: "Variance chip prefix" },
  { key: "invoices.form.varianceVs", default: "vs", group: "Invoice Form", label: "Variance chip: ‘vs’ separator" },
  { key: "invoices.form.addLine", default: "+ Add line", group: "Invoice Form", label: "‘Add line’ button" },
  { key: "invoices.form.recomputeHintPrefix", default: "Net weight and amounts recompute live — net = gross −", group: "Invoice Form", label: "Recompute hint prefix (before glazing term)", multiline: true },
  { key: "invoices.form.recomputeHintSuffix", default: "%, amount = net × rate.", group: "Invoice Form", label: "Recompute hint suffix", multiline: true },
  { key: "invoices.form.summary", default: "Summary", group: "Invoice Form", label: "Summary panel heading" },
  { key: "invoices.form.summaryReference", default: "Reference", group: "Invoice Form", label: "Summary row: Reference" },
  { key: "invoices.form.summaryReferenceEmpty", default: "—", group: "Invoice Form", label: "Summary: reference placeholder when not entered" },
  { key: "invoices.form.summaryChannel", default: "Channel", group: "Invoice Form", label: "Summary row: Channel" },
  { key: "invoices.form.summaryLines", default: "Lines", group: "Invoice Form", label: "Summary row: Lines" },
  { key: "invoices.form.summaryNetWeight", default: "Net weight", group: "Invoice Form", label: "Summary row: Net weight" },
  { key: "invoices.form.summarySourceStore", default: "Source store", group: "Invoice Form", label: "Summary: Source store label" },
  { key: "invoices.form.summaryTotal", default: "Total", group: "Invoice Form", label: "Summary: Total label" },
  { key: "invoices.form.saving", default: "Saving…", group: "Invoice Form", label: "Save button (pending)" },
  { key: "invoices.form.saveInvoice", default: "Save invoice", group: "Invoice Form", label: "Save button" },

  /* --------- Invoice detail (src/app/invoices/[id]/page.tsx) --------- */
  { key: "invoices.detail.backMine", default: "← My invoices", group: "Invoice Detail", label: "Back link (delivery)" },
  { key: "invoices.detail.backAll", default: "← All invoices", group: "Invoice Detail", label: "Back link (office)" },
  { key: "invoices.detail.invoicePrefix", default: "Invoice", group: "Invoice Detail", label: "Title ‘Invoice’ prefix (before #number)" },
  { key: "invoices.detail.edit", default: "Edit", group: "Invoice Detail", label: "‘Edit’ button" },
  { key: "invoices.detail.print", default: "Print", group: "Invoice Detail", label: "‘Print’ button" },
  { key: "invoices.detail.draftFromField", default: "Draft from the field", group: "Invoice Detail", label: "Draft banner heading (office)" },
  { key: "invoices.detail.draftFromFieldBody", default: " — entered by the delivery login. Review the figures (use Edit to correct — it appends a versioned record), then approve.", group: "Invoice Detail", label: "Draft banner body (office)", multiline: true },
  { key: "invoices.detail.awaitingApproval", default: "Awaiting office approval", group: "Invoice Detail", label: "Draft banner heading (delivery)" },
  { key: "invoices.detail.awaitingApprovalBody", default: " — you can still print it and attach the package photo below.", group: "Invoice Detail", label: "Draft banner body (delivery)", multiline: true },
  { key: "invoices.detail.cardChannel", default: "Channel", group: "Invoice Detail", label: "Stat card: Channel" },
  { key: "invoices.detail.cardStatus", default: "Status", group: "Invoice Detail", label: "Stat card: Status" },
  { key: "invoices.detail.cardVersion", default: "Version", group: "Invoice Detail", label: "Stat card: Version" },
  { key: "invoices.detail.cardSourceStore", default: "Source store", group: "Invoice Detail", label: "Stat card: Source store" },
  { key: "invoices.detail.colItem", default: "Item", group: "Invoice Detail", label: "Line table header: Item" },
  { key: "invoices.detail.colGross", default: "Gross", group: "Invoice Detail", label: "Line table header: Gross" },
  { key: "invoices.detail.colNet", default: "Net", group: "Invoice Detail", label: "Line table header: Net" },
  { key: "invoices.detail.colGlazing", default: "Glazing", group: "Invoice Detail", label: "Line table header: Glazing" },
  { key: "invoices.detail.colRate", default: "Rate / kg", group: "Invoice Detail", label: "Line table header: Rate / kg" },
  { key: "invoices.detail.colCartons", default: "Cartons", group: "Invoice Detail", label: "Line table header: Cartons" },
  { key: "invoices.detail.colPackets", default: "Packets", group: "Invoice Detail", label: "Line table header: Packets" },
  { key: "invoices.detail.colAmount", default: "Amount", group: "Invoice Detail", label: "Line table header: Amount" },
  { key: "invoices.detail.total", default: "Total", group: "Invoice Detail", label: "Line table footer: Total" },
  { key: "invoices.detail.notes", default: "Notes", group: "Invoice Detail", label: "Notes card heading" },
  { key: "invoices.detail.expenses", default: "Invoice expenses (internal)", group: "Invoice Detail", label: "Expenses card heading" },
  { key: "invoices.detail.expensesTotal", default: "Total", group: "Invoice Detail", label: "Expenses card total label" },
  { key: "invoices.detail.paymentsHeading", default: "Payments against this invoice", group: "Invoice Detail", label: "Payments card heading" },
  { key: "invoices.detail.paymentsNone", default: "None recorded yet.", group: "Invoice Detail", label: "Payments empty state" },
  { key: "invoices.detail.chequePrefix", default: " · Cheque ", group: "Invoice Detail", label: "Payment row: cheque prefix" },
  { key: "invoices.detail.partial", default: "partial", group: "Invoice Detail", label: "Payment row: ‘partial’ chip" },
  { key: "invoices.detail.balanceDue", default: "Balance due", group: "Invoice Detail", label: "Balance panel heading" },
  { key: "invoices.detail.balanceOf", default: "of", group: "Invoice Detail", label: "Balance panel: ‘of {total}’ prefix" },
  { key: "invoices.detail.balanceReceived", default: "received", group: "Invoice Detail", label: "Balance panel: ‘{pct}% received’ suffix" },
  { key: "invoices.detail.recordPayment", default: "Record payment", group: "Invoice Detail", label: "‘Record payment’ link" },
  { key: "invoices.detail.historyHeading", default: "Delivery record history", group: "Invoice Detail", label: "Delivery-record history heading" },
  { key: "invoices.detail.historyNote", default: "· append-only dispute defense", group: "Invoice Detail", label: "Delivery-record history sub-note" },
  { key: "invoices.detail.historyEmpty", default: "No delivery records.", group: "Invoice Detail", label: "Delivery-record history empty state" },
  { key: "invoices.detail.colVersion", default: "Version", group: "Invoice Detail", label: "History table header: Version" },
  { key: "invoices.detail.colDeliveredAt", default: "Delivered at", group: "Invoice Detail", label: "History table header: Delivered at" },
  { key: "invoices.detail.colHistoryTotal", default: "Total", group: "Invoice Detail", label: "History table header: Total" },
  { key: "invoices.detail.original", default: "original", group: "Invoice Detail", label: "History row: ‘original’ chip" },

  /* --------- Review controls (src/app/invoices/[id]/ReviewControls.tsx) --------- */
  { key: "invoices.review.approving", default: "Approving…", group: "Invoice Review", label: "Approve button (pending)" },
  { key: "invoices.review.approveDraft", default: "✓ Approve draft", group: "Invoice Review", label: "Approve button" },
  { key: "invoices.review.readError", default: "Could not read that image — try another photo.", group: "Invoice Review", label: "Photo read error" },
  { key: "invoices.review.photoHeading", default: "Package photo", group: "Invoice Review", label: "Photo section heading" },
  { key: "invoices.review.photoSubnote", default: "· delivery confirmation, optional", group: "Invoice Review", label: "Photo section sub-note" },
  { key: "invoices.review.photoAlt", default: "Delivered package", group: "Invoice Review", label: "Photo alt text" },
  { key: "invoices.review.uploading", default: "Uploading…", group: "Invoice Review", label: "Photo status: uploading" },
  { key: "invoices.review.photoAttached", default: "Attached to the latest delivery record. Tap to open.", group: "Invoice Review", label: "Photo status: attached", multiline: true },
  { key: "invoices.review.photoTake", default: "Take / choose a photo of the delivered package", group: "Invoice Review", label: "Photo upload prompt", multiline: true },
  { key: "invoices.review.photoCompressed", default: "compressed automatically · JPG/PNG", group: "Invoice Review", label: "Photo upload sub-note" },
  { key: "invoices.review.noPhoto", default: "No photo attached.", group: "Invoice Review", label: "Photo empty state" },

  /* --------- Edit page (src/app/invoices/[id]/edit/page.tsx) --------- */
  { key: "invoices.edit.backPrefix", default: "← Invoice", group: "Edit Invoice", label: "Back link prefix (before #number)" },
  { key: "invoices.edit.eyebrow", default: "Sales", group: "Edit Invoice", label: "Page eyebrow" },
  { key: "invoices.edit.titlePrefix", default: "Edit invoice", group: "Edit Invoice", label: "Page title prefix (before #number)" },
  { key: "invoices.edit.subtitle", default: "Goods arrived short? Adjust the lines below — amounts recompute through the shared billing engine, the invoice number stays the same, and a new versioned delivery record is appended.", group: "Edit Invoice", label: "Page subtitle", multiline: true },

  /* --------- Edit form (src/app/invoices/[id]/edit/EditInvoiceForm.tsx) --------- */
  { key: "invoices.editForm.labelParty", default: "Party", group: "Edit Invoice Form", label: "Field label: Party" },
  { key: "invoices.editForm.hintFixed", default: "fixed on edit", group: "Edit Invoice Form", label: "Field hint: fixed on edit" },
  { key: "invoices.editForm.labelChannel", default: "Channel", group: "Edit Invoice Form", label: "Field label: Channel" },
  { key: "invoices.editForm.channelNorth", default: "North (frozen)", group: "Edit Invoice Form", label: "Channel value: North" },
  { key: "invoices.editForm.channelLocal", default: "Local (fresh)", group: "Edit Invoice Form", label: "Channel value: Local" },
  { key: "invoices.editForm.colItem", default: "Item", group: "Edit Invoice Form", label: "Line table header: Item" },
  { key: "invoices.editForm.colCartons", default: "Cartons", group: "Edit Invoice Form", label: "Line table header: Cartons" },
  { key: "invoices.editForm.colGross", default: "Gross kg", group: "Edit Invoice Form", label: "Line table header: Gross kg" },
  { key: "invoices.editForm.colNetIn", default: "Net kg in", group: "Edit Invoice Form", label: "Line table header: Net kg in (north override field)" },
  { key: "invoices.editForm.colRate", default: "Rate", group: "Edit Invoice Form", label: "Line table header: Rate" },
  { key: "invoices.editForm.colNet", default: "Net kg", group: "Edit Invoice Form", label: "Line table header: Net kg (right col)" },
  { key: "invoices.editForm.colAmount", default: "Amount", group: "Edit Invoice Form", label: "Line table header: Amount" },
  { key: "invoices.editForm.selectItem", default: "Select…", group: "Edit Invoice Form", label: "Item select placeholder option" },
  { key: "invoices.editForm.netKgPlaceholder", default: "net kg", group: "Edit Invoice Form", label: "Net-weight input placeholder (north)" },
  { key: "invoices.editForm.removeLine", default: "Remove line", group: "Edit Invoice Form", label: "Remove-line button tooltip" },
  { key: "invoices.editForm.labelPackets", default: "Packets", group: "Edit Invoice Form", label: "Field label: Packets" },
  { key: "invoices.editForm.labelGlazing", default: "Glazing %", group: "Edit Invoice Form", label: "Field label: Glazing % (north override)" },
  { key: "invoices.editForm.hintOptional", default: "optional", group: "Edit Invoice Form", label: "Field hint: optional" },
  { key: "invoices.editForm.glazing", default: "Glazing:", group: "Edit Invoice Form", label: "Live line: Glazing label" },
  { key: "invoices.editForm.overDeduction", default: "⚠ Over-deduction", group: "Edit Invoice Form", label: "Variance chip prefix" },
  { key: "invoices.editForm.varianceVs", default: "vs", group: "Edit Invoice Form", label: "Variance chip: ‘vs’ separator" },
  { key: "invoices.editForm.addLine", default: "+ Add line", group: "Edit Invoice Form", label: "‘Add line’ button" },
  { key: "invoices.editForm.footNote", default: "The invoice number stays the same. A new versioned delivery record is appended for dispute defense — the previous record is preserved, never overwritten.", group: "Edit Invoice Form", label: "Footer note", multiline: true },
  { key: "invoices.editForm.summary", default: "Summary", group: "Edit Invoice Form", label: "Summary panel heading" },
  { key: "invoices.editForm.summaryInvoice", default: "Invoice", group: "Edit Invoice Form", label: "Summary row: Invoice" },
  { key: "invoices.editForm.summaryChannel", default: "Channel", group: "Edit Invoice Form", label: "Summary row: Channel" },
  { key: "invoices.editForm.summaryLines", default: "Lines", group: "Edit Invoice Form", label: "Summary row: Lines" },
  { key: "invoices.editForm.summaryNetWeight", default: "Net weight", group: "Edit Invoice Form", label: "Summary row: Net weight" },
  { key: "invoices.editForm.summaryNotes", default: "Notes", group: "Edit Invoice Form", label: "Summary: Notes label" },
  { key: "invoices.editForm.notesPlaceholder", default: "Notes (optional)", group: "Edit Invoice Form", label: "Notes input placeholder" },
  { key: "invoices.editForm.summaryTotal", default: "Total", group: "Edit Invoice Form", label: "Summary: Total label" },
  { key: "invoices.editForm.saving", default: "Saving…", group: "Edit Invoice Form", label: "Save button (pending)" },
  { key: "invoices.editForm.saveChanges", default: "Save changes to", group: "Edit Invoice Form", label: "Save button prefix (before #number)" },
  { key: "invoices.editForm.cancel", default: "Cancel", group: "Edit Invoice Form", label: "‘Cancel’ link" },

  /* --------- Print page (src/app/invoices/[id]/print/page.tsx) --------- */
  { key: "invoices.print.noteNorth", default: "North (frozen): billed on NET weight after glazing deduction. Net = gross × (1 − glazing%). Buyer's defrosted/final weight is the agreed basis.", group: "Invoice Print", label: "Channel note: North", multiline: true },
  { key: "invoices.print.noteLocal", default: "Local (fresh): billed on delivered weight. No glazing deduction applies (glazing% = 0).", group: "Invoice Print", label: "Channel note: Local", multiline: true },
  { key: "invoices.print.back", default: "← Back to invoice", group: "Invoice Print", label: "Back link" },
  { key: "invoices.print.tagline", default: "Seafood trading & distribution", group: "Invoice Print", label: "Company header tagline" },
  { key: "invoices.print.invoiceHeading", default: "INVOICE", group: "Invoice Print", label: "Document heading" },
  { key: "invoices.print.refPrefix", default: "Ref", group: "Invoice Print", label: "Reference number prefix" },
  { key: "invoices.print.billTo", default: "Bill to", group: "Invoice Print", label: "Bill-to label" },
  { key: "invoices.print.ntnPrefix", default: "NTN", group: "Invoice Print", label: "Bill-to: NTN number prefix" },
  { key: "invoices.print.noNtn", default: "No NTN (local party)", group: "Invoice Print", label: "Bill-to: no-NTN fallback" },
  { key: "invoices.print.colItem", default: "Item", group: "Invoice Print", label: "Line table header: Item" },
  { key: "invoices.print.colGross", default: "Gross", group: "Invoice Print", label: "Line table header: Gross" },
  { key: "invoices.print.colGlazing", default: "Glazing %", group: "Invoice Print", label: "Line table header: Glazing %" },
  { key: "invoices.print.colNet", default: "Net", group: "Invoice Print", label: "Line table header: Net" },
  { key: "invoices.print.colRate", default: "Rate / kg", group: "Invoice Print", label: "Line table header: Rate / kg" },
  { key: "invoices.print.colAmount", default: "Amount", group: "Invoice Print", label: "Line table header: Amount" },
  { key: "invoices.print.total", default: "Total", group: "Invoice Print", label: "Line table footer: Total" },
  { key: "invoices.print.notes", default: "Notes", group: "Invoice Print", label: "Notes block heading" },
  { key: "invoices.print.receivedBy", default: "Received by (signature)", group: "Invoice Print", label: "Signature line: received by" },
  { key: "invoices.print.dateLabel", default: "Date", group: "Invoice Print", label: "Signature line: date" },
];
