import type { CopyFragment } from "./types";

/**
 * Copy for the reports area. Each entry: a stable namespaced key, the English
 * default (source of truth), the editor group + a human label. Migration adds
 * entries here; render sites call t("<key>"). Keys MUST be globally unique.
 */
export const reportsCopy: CopyFragment = [
  // ---- Reports hub ----
  { key: "reports.hub.eyebrow", default: "Insight", group: "Reports", label: "Hub page eyebrow" },
  { key: "reports.hub.title", default: "Reports", group: "Reports", label: "Hub page title" },
  {
    key: "reports.hub.weekly.title",
    default: "Weekly statement",
    group: "Reports",
    label: "Hub card: Weekly statement title",
  },
  {
    key: "reports.hub.weekly.desc",
    default:
      "Who owes you and whom you owe, as of a date range — split corporate / local / suppliers. Printable / save as PDF.",
    group: "Reports",
    label: "Hub card: Weekly statement description",
    multiline: true,
  },
  {
    key: "reports.hub.badDebts.title",
    default: "Bad debts & disputes",
    group: "Reports",
    label: "Hub card: Bad debts & disputes title",
  },
  {
    key: "reports.hub.badDebts.desc",
    default:
      "Record write-offs and disputed amounts (linked to a party/invoice or free-text), split bad-debt vs dispute, with a printable summary.",
    group: "Reports",
    label: "Hub card: Bad debts & disputes description",
    multiline: true,
  },

  // ---- Bad debts & disputes ledger ----
  { key: "reports.badDebts.back", default: "← Reports", group: "Bad debts & disputes", label: "Back link" },
  { key: "reports.badDebts.eyebrow", default: "Insight", group: "Bad debts & disputes", label: "Page eyebrow" },
  {
    key: "reports.badDebts.title",
    default: "Bad debts & disputes",
    group: "Bad debts & disputes",
    label: "Page title",
  },
  {
    key: "reports.badDebts.subtitlePrefix",
    default: "Write-offs and disputed amounts for ",
    group: "Bad debts & disputes",
    label: "Subtitle (text before entity name)",
  },
  {
    key: "reports.badDebts.subtitleSuffix",
    default: " — link a party/invoice for dispute defense.",
    group: "Bad debts & disputes",
    label: "Subtitle (text after entity name)",
  },
  {
    key: "reports.badDebts.printSummary",
    default: "Print summary",
    group: "Bad debts & disputes",
    label: "Print summary link",
  },
  { key: "reports.badDebts.tab.all", default: "All", group: "Bad debts & disputes", label: "Filter tab: All" },
  {
    key: "reports.badDebts.tab.badDebt",
    default: "Bad debts",
    group: "Bad debts & disputes",
    label: "Filter tab: Bad debts",
  },
  {
    key: "reports.badDebts.tab.dispute",
    default: "Disputes",
    group: "Bad debts & disputes",
    label: "Filter tab: Disputes",
  },
  {
    key: "reports.badDebts.chip.dispute",
    default: "Dispute",
    group: "Bad debts & disputes",
    label: "Row type chip: Dispute",
  },
  {
    key: "reports.badDebts.chip.badDebt",
    default: "Bad debt",
    group: "Bad debts & disputes",
    label: "Row type chip: Bad debt",
  },
  {
    key: "reports.badDebts.summary.badDebts",
    default: "Bad debts",
    group: "Bad debts & disputes",
    label: "Summary card: Bad debts",
  },
  {
    key: "reports.badDebts.summary.disputed",
    default: "Disputed",
    group: "Bad debts & disputes",
    label: "Summary card: Disputed",
  },
  {
    key: "reports.badDebts.summary.grandTotal",
    default: "Grand total",
    group: "Bad debts & disputes",
    label: "Summary card: Grand total",
  },
  { key: "reports.badDebts.th.date", default: "Date", group: "Bad debts & disputes", label: "Table header: Date" },
  {
    key: "reports.badDebts.th.party",
    default: "Party / person",
    group: "Bad debts & disputes",
    label: "Table header: Party / person",
  },
  {
    key: "reports.badDebts.th.invoice",
    default: "Invoice",
    group: "Bad debts & disputes",
    label: "Table header: Invoice",
  },
  { key: "reports.badDebts.th.type", default: "Type", group: "Bad debts & disputes", label: "Table header: Type" },
  {
    key: "reports.badDebts.th.amount",
    default: "Amount",
    group: "Bad debts & disputes",
    label: "Table header: Amount",
  },
  { key: "reports.badDebts.th.note", default: "Note", group: "Bad debts & disputes", label: "Table header: Note" },
  {
    key: "reports.badDebts.th.actions",
    default: "Actions",
    group: "Bad debts & disputes",
    label: "Table header: Actions",
  },
  {
    key: "reports.badDebts.empty",
    default: "No entries",
    group: "Bad debts & disputes",
    label: "Empty state (text before optional filter suffix)",
  },
  {
    key: "reports.badDebts.emptyFilterSuffix",
    default: " for this filter",
    group: "Bad debts & disputes",
    label: "Empty state suffix when a filter is active",
  },

  // ---- Bad debts add/delete controls (client) ----
  {
    key: "reports.badDebts.addEntry",
    default: "+ Add entry",
    group: "Bad debts & disputes",
    label: "Open add-entry button",
  },
  {
    key: "reports.badDebts.form.title",
    default: "New entry",
    group: "Bad debts & disputes",
    label: "Add form heading",
  },
  { key: "reports.badDebts.form.close", default: "Close", group: "Bad debts & disputes", label: "Add form close button" },
  {
    key: "reports.badDebts.form.type",
    default: "Type",
    group: "Bad debts & disputes",
    label: "Sub-category toggle label",
  },
  {
    key: "reports.badDebts.form.toggleBadDebt",
    default: "Bad debt",
    group: "Bad debts & disputes",
    label: "Sub-category toggle: Bad debt",
  },
  {
    key: "reports.badDebts.form.toggleDispute",
    default: "Dispute",
    group: "Bad debts & disputes",
    label: "Sub-category toggle: Dispute",
  },
  {
    key: "reports.badDebts.form.amount",
    default: "Amount (PKR)",
    group: "Bad debts & disputes",
    label: "Field label: Amount",
  },
  { key: "reports.badDebts.form.party", default: "Party", group: "Bad debts & disputes", label: "Field label: Party" },
  {
    key: "reports.badDebts.form.partyHint",
    default: "optional — links a tracked party",
    group: "Bad debts & disputes",
    label: "Field hint: Party",
  },
  {
    key: "reports.badDebts.form.partyFreeText",
    default: "— free-text person —",
    group: "Bad debts & disputes",
    label: "Party select: free-text option",
  },
  {
    key: "reports.badDebts.form.partySupplierSuffix",
    default: " (supplier)",
    group: "Bad debts & disputes",
    label: "Party option supplier suffix",
  },
  {
    key: "reports.badDebts.form.personName",
    default: "Person name",
    group: "Bad debts & disputes",
    label: "Field label: Person name",
  },
  {
    key: "reports.badDebts.form.personNameHint",
    default: "required if no party",
    group: "Bad debts & disputes",
    label: "Field hint: Person name (no party selected)",
  },
  {
    key: "reports.badDebts.form.personNamePlaceholder",
    default: "e.g. Ali Traders",
    group: "Bad debts & disputes",
    label: "Field placeholder: Person name",
  },
  {
    key: "reports.badDebts.form.invoice",
    default: "Invoice",
    group: "Bad debts & disputes",
    label: "Field label: Invoice",
  },
  {
    key: "reports.badDebts.form.invoiceHint",
    default: "optional — dispute defense",
    group: "Bad debts & disputes",
    label: "Field hint: Invoice",
  },
  {
    key: "reports.badDebts.form.invoiceNone",
    default: "— none —",
    group: "Bad debts & disputes",
    label: "Invoice select: none option",
  },
  { key: "reports.badDebts.form.date", default: "Date", group: "Bad debts & disputes", label: "Field label: Date" },
  {
    key: "reports.badDebts.form.today",
    default: "Today",
    group: "Bad debts & disputes",
    label: "Set-date-to-today button",
  },
  { key: "reports.badDebts.form.note", default: "Note", group: "Bad debts & disputes", label: "Field label: Note" },
  {
    key: "reports.badDebts.form.noteHint",
    default: "optional",
    group: "Bad debts & disputes",
    label: "Field hint: Note",
  },
  {
    key: "reports.badDebts.form.saving",
    default: "Saving…",
    group: "Bad debts & disputes",
    label: "Submit button (saving state)",
  },
  {
    key: "reports.badDebts.form.submit",
    default: "Add entry",
    group: "Bad debts & disputes",
    label: "Submit button (idle state)",
  },
  {
    key: "reports.badDebts.form.saved",
    default: "✓ Saved.",
    group: "Bad debts & disputes",
    label: "Save confirmation",
  },
  {
    key: "reports.badDebts.delete.title",
    default: "Delete entry",
    group: "Bad debts & disputes",
    label: "Row delete button tooltip",
  },
  {
    key: "reports.badDebts.delete.label",
    default: "Delete",
    group: "Bad debts & disputes",
    label: "Row delete button label",
  },

  // ---- Bad debts print ----
  {
    key: "reports.badDebts.print.back",
    default: "← Back to ledger",
    group: "Bad debts print",
    label: "Back to ledger link",
  },
  {
    key: "reports.badDebts.print.tagline",
    default: "Seafood trading & distribution",
    group: "Bad debts print",
    label: "Header tagline",
  },
  {
    key: "reports.badDebts.print.heading",
    default: "BAD DEBTS & DISPUTES",
    group: "Bad debts print",
    label: "Sheet heading",
  },
  {
    key: "reports.badDebts.print.asOf",
    default: "as of ",
    group: "Bad debts print",
    label: "As-of label (before date)",
  },
  {
    key: "reports.badDebts.print.empty",
    default: "No bad-debt or dispute entries recorded.",
    group: "Bad debts print",
    label: "Empty state",
  },
  {
    key: "reports.badDebts.print.th.date",
    default: "Date",
    group: "Bad debts print",
    label: "Table header: Date",
  },
  {
    key: "reports.badDebts.print.th.party",
    default: "Party / person",
    group: "Bad debts print",
    label: "Table header: Party / person",
  },
  {
    key: "reports.badDebts.print.th.invoice",
    default: "Invoice",
    group: "Bad debts print",
    label: "Table header: Invoice",
  },
  {
    key: "reports.badDebts.print.th.amount",
    default: "Amount",
    group: "Bad debts print",
    label: "Table header: Amount",
  },
  {
    key: "reports.badDebts.print.th.note",
    default: "Note",
    group: "Bad debts print",
    label: "Table header: Note",
  },
  {
    key: "reports.badDebts.print.subtotalSuffix",
    default: " subtotal",
    group: "Bad debts print",
    label: "Group subtotal row (suffix after group title)",
  },
  {
    key: "reports.badDebts.print.grandTotal",
    default: "Grand total",
    group: "Bad debts print",
    label: "Grand total label",
  },

  // ---- Weekly statement ----
  { key: "reports.weekly.back", default: "← Reports", group: "Weekly statement", label: "Back link" },
  { key: "reports.weekly.eyebrow", default: "Insight", group: "Weekly statement", label: "Page eyebrow" },
  { key: "reports.weekly.title", default: "Weekly statement", group: "Weekly statement", label: "Page title" },
  {
    key: "reports.weekly.print",
    default: "Print / Save as PDF",
    group: "Weekly statement",
    label: "Print / Save as PDF button",
  },
  {
    key: "reports.weekly.preset.thisWeek",
    default: "This week",
    group: "Weekly statement",
    label: "Preset: This week",
  },
  {
    key: "reports.weekly.preset.lastWeek",
    default: "Last week",
    group: "Weekly statement",
    label: "Preset: Last week",
  },
  {
    key: "reports.weekly.preset.thisMonth",
    default: "This month",
    group: "Weekly statement",
    label: "Preset: This month",
  },
  {
    key: "reports.weekly.balancesAsOf",
    default: "balances as of",
    group: "Weekly statement",
    label: "Subtitle: balances as-of label (before date)",
  },
  { key: "reports.weekly.from", default: "From", group: "Weekly statement", label: "Date filter: From label" },
  { key: "reports.weekly.to", default: "To", group: "Weekly statement", label: "Date filter: To label" },
  { key: "reports.weekly.apply", default: "Apply", group: "Weekly statement", label: "Apply date filter button" },
  {
    key: "reports.weekly.receivables",
    default: "Receivables — owed to us",
    group: "Weekly statement",
    label: "Receivables section heading",
  },
  {
    key: "reports.weekly.corporate",
    default: "Corporate customers",
    group: "Weekly statement",
    label: "Receivables sub-table: Corporate customers",
  },
  {
    key: "reports.weekly.corporateEmpty",
    default: "No corporate customers with an outstanding balance.",
    group: "Weekly statement",
    label: "Empty state: Corporate customers",
  },
  {
    key: "reports.weekly.local",
    default: "Local customers",
    group: "Weekly statement",
    label: "Receivables sub-table: Local customers",
  },
  {
    key: "reports.weekly.localEmpty",
    default: "No local customers with an outstanding balance.",
    group: "Weekly statement",
    label: "Empty state: Local customers",
  },
  {
    key: "reports.weekly.payables",
    default: "Payables — we owe",
    group: "Weekly statement",
    label: "Payables section heading",
  },
  { key: "reports.weekly.suppliers", default: "Suppliers", group: "Weekly statement", label: "Payables table heading" },
  {
    key: "reports.weekly.suppliersEmpty",
    default: "No suppliers with an outstanding balance.",
    group: "Weekly statement",
    label: "Empty state: Suppliers",
  },
  {
    key: "reports.weekly.th.party",
    default: "Party",
    group: "Weekly statement",
    label: "Table header: Party",
  },
  {
    key: "reports.weekly.th.openInvoices",
    default: "Open invoices",
    group: "Weekly statement",
    label: "Table header: Open invoices",
  },
  {
    key: "reports.weekly.th.outstanding",
    default: "Outstanding",
    group: "Weekly statement",
    label: "Table header: Outstanding",
  },
  {
    key: "reports.weekly.th.supplier",
    default: "Supplier",
    group: "Weekly statement",
    label: "Table header: Supplier",
  },
  {
    key: "reports.weekly.subtotal",
    default: "Subtotal",
    group: "Weekly statement",
    label: "Subtotal row label",
  },
  {
    key: "reports.weekly.netPosition",
    default: "Net position (receivables − payables)",
    group: "Weekly statement",
    label: "Net position label",
  },
  {
    key: "reports.weekly.netHintPrefix",
    default: "Positive = net owed to us. ",
    group: "Weekly statement",
    label: "Net position hint (text before receivable amount)",
  },
  {
    key: "reports.weekly.netHintReceivable",
    default: " receivable − ",
    group: "Weekly statement",
    label: "Net position hint (between amounts)",
  },
  {
    key: "reports.weekly.netHintPayable",
    default: " payable.",
    group: "Weekly statement",
    label: "Net position hint (after payable amount)",
  },

  // ---- Weekly statement print ----
  {
    key: "reports.weekly.print.back",
    default: "← Back to statement",
    group: "Weekly statement print",
    label: "Back to statement link",
  },
  {
    key: "reports.weekly.print.tagline",
    default: "Seafood trading & distribution",
    group: "Weekly statement print",
    label: "Header tagline",
  },
  {
    key: "reports.weekly.print.heading",
    default: "WEEKLY STATEMENT",
    group: "Weekly statement print",
    label: "Sheet heading",
  },
  {
    key: "reports.weekly.print.balancesAsOf",
    default: "Balances as of ",
    group: "Weekly statement print",
    label: "Balances as-of label (before date)",
  },
  {
    key: "reports.weekly.print.receivables",
    default: "Receivables — owed to us",
    group: "Weekly statement print",
    label: "Receivables section heading",
  },
  {
    key: "reports.weekly.print.corporate",
    default: "Corporate customers",
    group: "Weekly statement print",
    label: "Receivables sub-section: Corporate customers",
  },
  {
    key: "reports.weekly.print.local",
    default: "Local customers",
    group: "Weekly statement print",
    label: "Receivables sub-section: Local customers",
  },
  {
    key: "reports.weekly.print.payables",
    default: "Payables — we owe",
    group: "Weekly statement print",
    label: "Payables section heading",
  },
  {
    key: "reports.weekly.print.suppliers",
    default: "Suppliers",
    group: "Weekly statement print",
    label: "Payables sub-section: Suppliers",
  },
  {
    key: "reports.weekly.print.sectionEmpty",
    default: "No outstanding balance.",
    group: "Weekly statement print",
    label: "Empty state for a section",
  },
  {
    key: "reports.weekly.print.th.party",
    default: "Party",
    group: "Weekly statement print",
    label: "Table header: Party",
  },
  {
    key: "reports.weekly.print.th.openInvoices",
    default: "Open invoices",
    group: "Weekly statement print",
    label: "Table header: Open invoices",
  },
  {
    key: "reports.weekly.print.th.outstanding",
    default: "Outstanding",
    group: "Weekly statement print",
    label: "Table header: Outstanding",
  },
  {
    key: "reports.weekly.print.th.supplier",
    default: "Supplier",
    group: "Weekly statement print",
    label: "Table header: Supplier",
  },
  {
    key: "reports.weekly.print.subtotal",
    default: "Subtotal",
    group: "Weekly statement print",
    label: "Subtotal row label",
  },
  {
    key: "reports.weekly.print.netPosition",
    default: "Net position (receivables − payables)",
    group: "Weekly statement print",
    label: "Net position label",
  },
];
