import type { CopyFragment } from "./types";

/**
 * Copy for the settings area. Each entry: a stable namespaced key, the English
 * default (source of truth), the editor group + a human label. Migration adds
 * entries here; render sites call t("<key>"). Keys MUST be globally unique.
 */
export const settingsCopy: CopyFragment = [
  /* ===================== Settings hub ===================== */
  { key: "settings.hub.eyebrow", default: "Admin", group: "Settings hub", label: "Page eyebrow" },
  { key: "settings.hub.title", default: "Settings", group: "Settings hub", label: "Page title" },
  {
    key: "settings.hub.subtitle.prefix",
    default: "Master data for ",
    group: "Settings hub",
    label: "Subtitle — text before the book name",
  },
  {
    key: "settings.hub.subtitle.suffix",
    default:
      ". Add, rename and fine-tune the stores, parties, products and numbering your book uses.",
    group: "Settings hub",
    label: "Subtitle — text after the book name",
    multiline: true,
  },
  { key: "settings.hub.stores.title", default: "Stores", group: "Settings hub", label: "Stores card title" },
  {
    key: "settings.hub.stores.desc",
    default: "Add stores; rename an existing one (no delete — FK-safe).",
    group: "Settings hub",
    label: "Stores card description",
  },
  {
    key: "settings.hub.parties.title",
    default: "Parties & suppliers",
    group: "Settings hub",
    label: "Parties card title",
  },
  {
    key: "settings.hub.parties.desc",
    default: "Customers and suppliers — add, edit, opening balances, NTN.",
    group: "Settings hub",
    label: "Parties card description",
  },
  {
    key: "settings.hub.items.title",
    default: "Items / products",
    group: "Settings hub",
    label: "Items card title",
  },
  {
    key: "settings.hub.items.desc",
    default: "Fish fillet & prawn products; rates and glazing are owner-confirmable.",
    group: "Settings hub",
    label: "Items card description",
  },
  {
    key: "settings.hub.references.title",
    default: "Reference series",
    group: "Settings hub",
    label: "Reference series card title",
  },
  {
    key: "settings.hub.references.desc",
    default: "Per-book/region manual invoice numbering with a live preview.",
    group: "Settings hub",
    label: "Reference series card description",
  },
  { key: "settings.hub.users.title", default: "Users", group: "Settings hub", label: "Users card title" },
  {
    key: "settings.hub.users.desc",
    default: "Staff logins, roles, book access and region scope (admin only).",
    group: "Settings hub",
    label: "Users card description",
  },
  {
    key: "settings.hub.users.lockedChip",
    default: "admin only",
    group: "Settings hub",
    label: "Users card — locked chip (non-admin)",
  },
  {
    key: "settings.hub.users.lockedDesc",
    default: "Only an admin may manage staff logins and roles.",
    group: "Settings hub",
    label: "Users card — locked description (non-admin)",
  },
  {
    key: "settings.hub.elsewhere.title",
    default: "Also managed elsewhere",
    group: "Settings hub",
    label: "Cross-links card title",
  },
  {
    key: "settings.hub.elsewhere.desc",
    default:
      "These live on their own pages so this stays the single hub for everything you can customise.",
    group: "Settings hub",
    label: "Cross-links card description",
    multiline: true,
  },
  {
    key: "settings.hub.link.banks",
    default: "Bank accounts →",
    group: "Settings hub",
    label: "Cross-link — Bank accounts",
  },
  {
    key: "settings.hub.link.expenses",
    default: "Expense categories →",
    group: "Settings hub",
    label: "Cross-link — Expense categories",
  },
  {
    key: "settings.hub.link.password",
    default: "Change my password →",
    group: "Settings hub",
    label: "Cross-link — Change my password",
  },

  /* ===================== Shared bits ===================== */
  { key: "settings.backLink", default: "← Settings", group: "Settings shared", label: "Back link to hub" },
  { key: "settings.editToggle.close", default: "Close", group: "Settings shared", label: "Edit-toggle — Close button" },
  { key: "settings.editToggle.edit", default: "Edit", group: "Settings shared", label: "Edit-toggle — Edit button" },

  /* ===================== Change password ===================== */
  { key: "settings.password.eyebrow", default: "Admin", group: "Change password", label: "Page eyebrow" },
  { key: "settings.password.title", default: "Change password", group: "Change password", label: "Page title" },
  {
    key: "settings.password.subtitle.prefix",
    default: "Signed in as ",
    group: "Change password",
    label: "Subtitle — text before the user name",
  },
  {
    key: "settings.password.subtitle.suffix",
    default:
      ". Changing your password does not log out other devices (rotate the server secret for that).",
    group: "Change password",
    label: "Subtitle — text after the user name",
    multiline: true,
  },
  {
    key: "settings.password.currentLabel",
    default: "Current password",
    group: "Change password",
    label: "Current password field label",
  },
  {
    key: "settings.password.newLabel",
    default: "New password",
    group: "Change password",
    label: "New password field label",
  },
  {
    key: "settings.password.newHint",
    default: "min 6 characters",
    group: "Change password",
    label: "New password field hint",
  },
  {
    key: "settings.password.confirmLabel",
    default: "Confirm new password",
    group: "Change password",
    label: "Confirm password field label",
  },
  {
    key: "settings.password.ok",
    default: "✓ Password changed.",
    group: "Change password",
    label: "Success message",
  },
  {
    key: "settings.password.saving",
    default: "Saving…",
    group: "Change password",
    label: "Submit button — saving state",
  },
  {
    key: "settings.password.submit",
    default: "Change password",
    group: "Change password",
    label: "Submit button label",
  },

  /* ===================== Reference series ===================== */
  { key: "settings.references.eyebrow", default: "Admin", group: "Reference series", label: "Page eyebrow" },
  {
    key: "settings.references.title",
    default: "Reference series",
    group: "Reference series",
    label: "Page title",
  },
  {
    key: "settings.references.subtitle.prefix",
    default:
      "Per-book/region manual invoice numbering (one series per region). The ",
    group: "Reference series",
    label: "Subtitle — text before ‘current number’",
    multiline: true,
  },
  {
    key: "settings.references.subtitle.currentNumber",
    default: "current number",
    group: "Reference series",
    label: "Subtitle — emphasised ‘current number’",
  },
  {
    key: "settings.references.subtitle.suffix",
    default:
      " is where the book stands now — invoicing bumps it by one and formats the preview shown.",
    group: "Reference series",
    label: "Subtitle — text after ‘current number’",
    multiline: true,
  },
  {
    key: "settings.references.existingHeading",
    default: "Existing series",
    group: "Reference series",
    label: "Existing series card heading",
  },
  {
    key: "settings.references.addHeading",
    default: "Add series",
    group: "Reference series",
    label: "Add series card heading",
  },
  {
    key: "settings.references.preview.label",
    default: "Next number: ",
    group: "Reference series",
    label: "Live preview — label",
  },
  {
    key: "settings.references.field.prefix",
    default: "Prefix",
    group: "Reference series",
    label: "Prefix field label",
  },
  {
    key: "settings.references.field.prefixHint",
    default: "e.g. SSI-",
    group: "Reference series",
    label: "Prefix field hint",
  },
  {
    key: "settings.references.field.region",
    default: "Book / region",
    group: "Reference series",
    label: "Book/region field label",
  },
  {
    key: "settings.references.field.regionHint",
    default: "e.g. Karachi",
    group: "Reference series",
    label: "Book/region field hint",
  },
  {
    key: "settings.references.field.current",
    default: "Current number",
    group: "Reference series",
    label: "Current number field label",
  },
  {
    key: "settings.references.field.width",
    default: "Digit width",
    group: "Reference series",
    label: "Digit width field label",
  },
  {
    key: "settings.references.add.adding",
    default: "Adding…",
    group: "Reference series",
    label: "Add button — adding state",
  },
  {
    key: "settings.references.add.submit",
    default: "+ Add series",
    group: "Reference series",
    label: "Add button label",
  },
  {
    key: "settings.references.saved",
    default: "✓ Saved.",
    group: "Reference series",
    label: "Add — saved message",
  },
  {
    key: "settings.references.edit.saving",
    default: "Saving…",
    group: "Reference series",
    label: "Edit save button — saving state",
  },
  {
    key: "settings.references.edit.save",
    default: "Save",
    group: "Reference series",
    label: "Edit save button label",
  },
  {
    key: "settings.references.empty",
    default: "No reference series yet — add one below.",
    group: "Reference series",
    label: "Empty-state message",
  },
  {
    key: "settings.references.row.next",
    default: "next",
    group: "Reference series",
    label: "Row summary — ‘next’ label",
  },
  {
    key: "settings.references.row.at",
    default: "at",
    group: "Reference series",
    label: "Row summary — ‘at’ label",
  },

  /* ===================== Stores ===================== */
  { key: "settings.stores.eyebrow", default: "Admin", group: "Stores", label: "Page eyebrow" },
  { key: "settings.stores.title", default: "Stores", group: "Stores", label: "Page title" },
  {
    key: "settings.stores.subtitle",
    default:
      "Stores can be renamed but not deleted — they are referenced by invoices, inventory and shipments.",
    group: "Stores",
    label: "Page subtitle",
    multiline: true,
  },
  {
    key: "settings.stores.existingHeading",
    default: "Existing stores",
    group: "Stores",
    label: "Existing stores card heading",
  },
  { key: "settings.stores.addHeading", default: "Add store", group: "Stores", label: "Add store card heading" },
  { key: "settings.stores.field.name", default: "Name", group: "Stores", label: "Name field label" },
  { key: "settings.stores.field.city", default: "City", group: "Stores", label: "City field label" },
  {
    key: "settings.stores.field.cityHint",
    default: "optional",
    group: "Stores",
    label: "City field hint",
  },
  { key: "settings.stores.field.region", default: "Region", group: "Stores", label: "Region field label" },
  {
    key: "settings.stores.field.regionHint",
    default: "optional",
    group: "Stores",
    label: "Region field hint (add form)",
  },
  {
    key: "settings.stores.field.ownership",
    default: "Ownership",
    group: "Stores",
    label: "Ownership field label",
  },
  { key: "settings.stores.field.capabilities", default: "Processes done here", group: "Stores", label: "Process capabilities field label" },
  { key: "settings.stores.field.capabilitiesHint", default: "what this store can do in-house", group: "Stores", label: "Process capabilities field hint" },
  { key: "settings.stores.row.doesPrefix", default: "does", group: "Stores", label: "Row summary — capabilities prefix" },
  { key: "settings.stores.add.adding", default: "Adding…", group: "Stores", label: "Add button — adding state" },
  { key: "settings.stores.add.submit", default: "+ Add store", group: "Stores", label: "Add button label" },
  { key: "settings.stores.saved", default: "✓ Saved.", group: "Stores", label: "Add — saved message" },
  {
    key: "settings.stores.edit.saving",
    default: "Saving…",
    group: "Stores",
    label: "Edit save button — saving state",
  },
  { key: "settings.stores.edit.save", default: "Save", group: "Stores", label: "Edit save button label" },
  {
    key: "settings.stores.empty",
    default: "No stores yet — add one below.",
    group: "Stores",
    label: "Empty-state message",
  },

  /* ===================== Users ===================== */
  { key: "settings.users.eyebrow", default: "Admin", group: "Users", label: "Page eyebrow" },
  { key: "settings.users.title", default: "Users", group: "Users", label: "Page title" },
  {
    key: "settings.users.subtitle.prefix",
    default: "Staff logins, roles and access for ",
    group: "Users",
    label: "Subtitle — text before the book name",
  },
  {
    key: "settings.users.subtitle.suffix",
    default:
      ". Passwords are hashed and never shown — leave the field blank when editing to keep the current one.",
    group: "Users",
    label: "Subtitle — text after the book name",
    multiline: true,
  },
  {
    key: "settings.users.existingHeading",
    default: "Existing users",
    group: "Users",
    label: "Existing users card heading",
  },
  { key: "settings.users.addHeading", default: "Add user", group: "Users", label: "Add user card heading" },
  { key: "settings.users.field.name", default: "Name", group: "Users", label: "Name field label" },
  { key: "settings.users.field.loginId", default: "Login ID", group: "Users", label: "Login ID field label" },
  { key: "settings.users.field.password", default: "Password", group: "Users", label: "Password field label" },
  { key: "settings.users.field.role", default: "Role", group: "Users", label: "Role field label" },
  {
    key: "settings.users.field.access",
    default: "Book access",
    group: "Users",
    label: "Book access field label",
  },
  {
    key: "settings.users.field.region",
    default: "Region scope",
    group: "Users",
    label: "Region scope field label",
  },
  {
    key: "settings.users.passwordHint.add",
    default: "min 4 chars — hashed on save",
    group: "Users",
    label: "Password hint — add form",
  },
  {
    key: "settings.users.passwordHint.edit",
    default: "leave blank to keep current",
    group: "Users",
    label: "Password hint — edit form",
  },
  { key: "settings.users.add.adding", default: "Adding…", group: "Users", label: "Add button — adding state" },
  { key: "settings.users.add.submit", default: "+ Add user", group: "Users", label: "Add button label" },
  { key: "settings.users.saved", default: "✓ Saved.", group: "Users", label: "Add — saved message" },
  {
    key: "settings.users.edit.saving",
    default: "Saving…",
    group: "Users",
    label: "Edit save button — saving state",
  },
  { key: "settings.users.edit.save", default: "Save", group: "Users", label: "Edit save button label" },
  {
    key: "settings.users.empty",
    default: "No users yet — add one below.",
    group: "Users",
    label: "Empty-state message",
  },
  { key: "settings.users.row.access", default: "access", group: "Users", label: "Row summary — ‘access’ prefix" },
  { key: "settings.users.row.region", default: "region", group: "Users", label: "Row summary — ‘region’ prefix" },

  /* ===================== Parties ===================== */
  { key: "settings.parties.eyebrow", default: "Admin", group: "Parties", label: "Page eyebrow" },
  {
    key: "settings.parties.title",
    default: "Parties & suppliers",
    group: "Parties",
    label: "Page title",
  },
  {
    key: "settings.parties.subtitle",
    default:
      "Add and edit customers and suppliers. Local buyers can be name-only (leave NTN blank); opening balances feed the ledgers.",
    group: "Parties",
    label: "Page subtitle",
    multiline: true,
  },
  {
    key: "settings.parties.customersTitle",
    default: "Customers",
    group: "Parties",
    label: "Customers list title",
  },
  {
    key: "settings.parties.suppliersTitle",
    default: "Suppliers",
    group: "Parties",
    label: "Suppliers list title",
  },
  {
    key: "settings.parties.addHeading",
    default: "Add party / supplier",
    group: "Parties",
    label: "Add party card heading",
  },
  { key: "settings.parties.field.name", default: "Name", group: "Parties", label: "Name field label" },
  { key: "settings.parties.field.type", default: "Type", group: "Parties", label: "Type field label" },
  {
    key: "settings.parties.field.subType",
    default: "Sub-type",
    group: "Parties",
    label: "Sub-type field label",
  },
  {
    key: "settings.parties.field.subTypeHintCustomer",
    default: "customers only",
    group: "Parties",
    label: "Sub-type hint — customer",
  },
  {
    key: "settings.parties.field.subTypeHintSupplier",
    default: "n/a for suppliers",
    group: "Parties",
    label: "Sub-type hint — supplier",
  },
  { key: "settings.parties.field.channel", default: "Channel", group: "Parties", label: "Channel field label" },
  {
    key: "settings.parties.field.channelHint",
    default: "optional",
    group: "Parties",
    label: "Channel field hint",
  },
  { key: "settings.parties.field.ntn", default: "NTN", group: "Parties", label: "NTN field label" },
  {
    key: "settings.parties.field.ntnHint",
    default: "local buyers are name-only — leave blank",
    group: "Parties",
    label: "NTN field hint",
  },
  {
    key: "settings.parties.field.opening",
    default: "Opening balance (PKR)",
    group: "Parties",
    label: "Opening balance field label",
  },
  {
    key: "settings.parties.field.openingHint",
    default: "optional",
    group: "Parties",
    label: "Opening balance field hint",
  },
  { key: "settings.parties.field.address", default: "Address", group: "Parties", label: "Address field label" },
  {
    key: "settings.parties.field.addressHint",
    default: "optional",
    group: "Parties",
    label: "Address field hint",
  },
  { key: "settings.parties.field.phone", default: "Phone", group: "Parties", label: "Phone field label" },
  { key: "settings.parties.field.email", default: "Email", group: "Parties", label: "Email field label" },
  {
    key: "settings.parties.field.contactPerson",
    default: "Contact person",
    group: "Parties",
    label: "Contact person field label",
  },
  { key: "settings.parties.add.adding", default: "Adding…", group: "Parties", label: "Add button — adding state" },
  { key: "settings.parties.add.submit", default: "+ Add party", group: "Parties", label: "Add button label" },
  { key: "settings.parties.saved", default: "✓ Saved.", group: "Parties", label: "Add — saved message" },
  {
    key: "settings.parties.edit.saving",
    default: "Saving…",
    group: "Parties",
    label: "Edit save button — saving state",
  },
  { key: "settings.parties.edit.save", default: "Save", group: "Parties", label: "Edit save button label" },
  {
    key: "settings.parties.empty",
    default: "None yet.",
    group: "Parties",
    label: "Empty-state message (per list)",
  },
  {
    key: "settings.parties.row.ntnPrefix",
    default: "NTN",
    group: "Parties",
    label: "Row summary — ‘NTN’ prefix",
  },
  {
    key: "settings.parties.row.openingPrefix",
    default: "opening",
    group: "Parties",
    label: "Row summary — ‘opening’ prefix",
  },

  /* ===================== Items ===================== */
  { key: "settings.items.eyebrow", default: "Admin", group: "Items", label: "Page eyebrow" },
  { key: "settings.items.title", default: "Items / products", group: "Items", label: "Page title" },
  {
    key: "settings.items.subtitle.prefix",
    default: "Fish-fillet and prawn products. Fixed rates and default glazing % are ",
    group: "Items",
    label: "Subtitle — text before ‘owner-confirmable’",
    multiline: true,
  },
  {
    key: "settings.items.subtitle.ownerConfirmable",
    default: "owner-confirmable",
    group: "Items",
    label: "Subtitle — emphasised ‘owner-confirmable’",
  },
  {
    key: "settings.items.subtitle.suffix",
    default:
      " — leave them blank until confirmed. Items are deactivated, not deleted (they appear in invoice history).",
    group: "Items",
    label: "Subtitle — text after ‘owner-confirmable’",
    multiline: true,
  },
  {
    key: "settings.items.existingHeading",
    default: "Existing items",
    group: "Items",
    label: "Existing items card heading",
  },
  { key: "settings.items.addHeading", default: "Add item", group: "Items", label: "Add item card heading" },
  { key: "settings.items.field.name", default: "Name", group: "Items", label: "Name field label" },
  { key: "settings.items.field.nature", default: "Nature", group: "Items", label: "Nature (raw/processed) field label" },
  { key: "settings.items.field.natureHint", default: "raw material or finished product", group: "Items", label: "Nature field hint" },
  { key: "settings.items.nature.raw", default: "Raw", group: "Items", label: "Nature option — raw" },
  { key: "settings.items.nature.processed", default: "Processed", group: "Items", label: "Nature option — processed" },
  { key: "settings.items.chip.raw", default: "raw", group: "Items", label: "Row chip — raw item" },
  { key: "settings.items.mkRaw", default: "+ Raw counterpart", group: "Items", label: "Create raw counterpart button" },
  { key: "settings.items.field.category", default: "Category", group: "Items", label: "Category field label" },
  {
    key: "settings.items.field.cartonKg",
    default: "Carton weight (kg)",
    group: "Items",
    label: "Carton weight field label",
  },
  {
    key: "settings.items.field.packets",
    default: "Packets / carton",
    group: "Items",
    label: "Packets per carton field label",
  },
  {
    key: "settings.items.field.rate",
    default: "Fixed rate (PKR/kg)",
    group: "Items",
    label: "Fixed rate field label",
  },
  {
    key: "settings.items.field.rateHint",
    default: "owner-confirmable · optional",
    group: "Items",
    label: "Fixed rate field hint",
  },
  {
    key: "settings.items.field.glazing",
    default: "Default glazing %",
    group: "Items",
    label: "Default glazing field label",
  },
  {
    key: "settings.items.field.glazingHint",
    default: "owner-confirmable · optional",
    group: "Items",
    label: "Default glazing field hint",
  },
  {
    key: "settings.items.field.isPrawn",
    default: "Is prawn (uses water-percent billing)",
    group: "Items",
    label: "Is-prawn checkbox label",
  },
  { key: "settings.items.add.adding", default: "Adding…", group: "Items", label: "Add button — adding state" },
  { key: "settings.items.add.submit", default: "+ Add item", group: "Items", label: "Add button label" },
  { key: "settings.items.saved", default: "✓ Saved.", group: "Items", label: "Add — saved message" },
  {
    key: "settings.items.edit.saving",
    default: "Saving…",
    group: "Items",
    label: "Edit save button — saving state",
  },
  { key: "settings.items.edit.save", default: "Save", group: "Items", label: "Edit save button label" },
  {
    key: "settings.items.chip.inactive",
    default: "inactive",
    group: "Items",
    label: "Row chip — inactive",
  },
  { key: "settings.items.chip.prawn", default: "prawn", group: "Items", label: "Row chip — prawn" },
  {
    key: "settings.items.toggle.deactivate",
    default: "Deactivate",
    group: "Items",
    label: "Active toggle — Deactivate",
  },
  {
    key: "settings.items.toggle.reactivate",
    default: "Reactivate",
    group: "Items",
    label: "Active toggle — Reactivate",
  },
  {
    key: "settings.items.editDetails",
    default: "Edit details",
    group: "Items",
    label: "Row — edit details toggle summary",
  },
  {
    key: "settings.items.empty",
    default: "No items yet — add one below.",
    group: "Items",
    label: "Empty-state message",
  },

  /* ===================== Danger zone — data reset ===================== */
  { key: "settings.hub.danger.title", default: "Danger zone", group: "Danger zone", label: "Hub danger card title" },
  {
    key: "settings.hub.danger.desc",
    default: "Permanently erase all data in this book to start fresh.",
    group: "Danger zone",
    label: "Hub danger card description",
  },
  { key: "settings.hub.danger.link", default: "Reset all data →", group: "Danger zone", label: "Hub danger card link" },
  { key: "settings.reset.eyebrow", default: "Danger zone", group: "Danger zone", label: "Reset page eyebrow" },
  { key: "settings.reset.title", default: "Reset all data", group: "Danger zone", label: "Reset page title" },
  { key: "settings.reset.subtitle.prefix", default: "This permanently deletes every business record in ", group: "Danger zone", label: "Reset subtitle — before book name" },
  {
    key: "settings.reset.subtitle.suffix",
    default: ". There is no undo — export anything you need first.",
    group: "Danger zone",
    label: "Reset subtitle — after book name",
    multiline: true,
  },
  { key: "settings.reset.warnTitle", default: "This cannot be undone", group: "Danger zone", label: "Warning card title" },
  {
    key: "settings.reset.warnBody",
    default: "Everything below will be permanently deleted from this book:",
    group: "Danger zone",
    label: "Warning card body",
    multiline: true,
  },
  {
    key: "settings.reset.keepNote",
    default: "Kept: login accounts, roles, app settings, expense categories and bank accounts. Invoice and purchase numbering restarts from 1.",
    group: "Danger zone",
    label: "What is preserved note",
    multiline: true,
  },
  { key: "settings.reset.count.parties", default: "Customers & suppliers", group: "Danger zone", label: "Count row — parties" },
  { key: "settings.reset.count.items", default: "Items", group: "Danger zone", label: "Count row — items" },
  { key: "settings.reset.count.stores", default: "Stores", group: "Danger zone", label: "Count row — stores" },
  { key: "settings.reset.count.invoices", default: "Invoices", group: "Danger zone", label: "Count row — invoices" },
  { key: "settings.reset.count.purchases", default: "Purchases", group: "Danger zone", label: "Count row — purchases" },
  { key: "settings.reset.count.deliveries", default: "Delivery records", group: "Danger zone", label: "Count row — deliveries" },
  { key: "settings.reset.count.shipments", default: "Shipments", group: "Danger zone", label: "Count row — shipments" },
  {
    key: "settings.reset.confirmLabel",
    default: "Type “{name}” to confirm",
    group: "Danger zone",
    label: "Confirm input label (uses {name})",
  },
  { key: "settings.reset.submit", default: "Delete all data", group: "Danger zone", label: "Reset submit button" },
  { key: "settings.reset.working", default: "Deleting…", group: "Danger zone", label: "Reset submit button (pending)" },
  {
    key: "settings.reset.done",
    default: "Done — {n} records permanently deleted. This book is now empty.",
    group: "Danger zone",
    label: "Reset success message (uses {n})",
  },
];
