/*
 * Client-side PDF builders (jsPDF + autotable). This module is dynamically
 * imported by SharePdfButton so the ~150KB of jsPDF never lands in the main
 * bundle. Currency/date use the app's shared formatters so PDFs match the UI.
 */
import { jsPDF } from "jspdf";
import { autoTable } from "jspdf-autotable";
import { pkr, kg, dateShort } from "@/lib/format";
import type {
  PdfKind,
  PdfPayload,
  InvoicePdfData,
  StatementPdfData,
  WeeklyPdfData,
  BadDebtsPdfData,
  WeeklyPdfRow,
} from "./types";

const INK = "#16262e";
const ACCENT = "#0e7c7b";
const MUTED = "#6b7a80";
const MARGIN = 40;

type RGB = [number, number, number];
const ACCENT_RGB: RGB = [14, 124, 123];
const ROW_RGB: RGB = [247, 244, 236];
const INK_RGB: RGB = [30, 40, 45];
const HAIR_RGB: RGB = [225, 220, 205];

function newDoc(): jsPDF {
  return new jsPDF({ unit: "pt", format: "a4" });
}
function pageW(doc: jsPDF): number {
  return doc.internal.pageSize.getWidth();
}
function lastY(doc: jsPDF): number {
  return (doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? 84;
}

function header(doc: jsPDF, business: string, title: string, subtitle?: string): number {
  const w = pageW(doc);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(INK);
  doc.setFontSize(18);
  doc.text(business, MARGIN, 50);

  doc.setFontSize(13);
  doc.setTextColor(ACCENT);
  doc.text(title, w - MARGIN, 46, { align: "right" });
  if (subtitle) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(MUTED);
    doc.text(subtitle, w - MARGIN, 60, { align: "right" });
  }
  doc.setDrawColor(ACCENT);
  doc.setLineWidth(1.4);
  doc.line(MARGIN, 66, w - MARGIN, 66);
  return 86;
}

function metaBlock(doc: jsPDF, lines: string[], startY: number): number {
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(INK);
  let y = startY;
  for (const l of lines) {
    doc.text(l, MARGIN, y);
    y += 15;
  }
  return y + 6;
}

const tableOpts = () =>
  ({
    theme: "grid" as const,
    headStyles: { fillColor: ACCENT_RGB, textColor: 255, fontStyle: "bold" as const, fontSize: 9 },
    styles: { fontSize: 9, cellPadding: 5, textColor: INK_RGB, lineColor: HAIR_RGB, lineWidth: 0.5 },
    alternateRowStyles: { fillColor: ROW_RGB },
    margin: { left: MARGIN, right: MARGIN },
  });

/** Right-aligned label/value summary rows; last row emphasised. */
function totals(doc: jsPDF, rows: [string, string][], startY: number): number {
  const w = pageW(doc);
  let y = startY;
  doc.setFontSize(10);
  rows.forEach(([label, val], i) => {
    const emphasise = i === rows.length - 1;
    doc.setFont("helvetica", emphasise ? "bold" : "normal");
    doc.setTextColor(emphasise ? INK : MUTED);
    doc.text(label, w - MARGIN - 160, y);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(INK);
    doc.text(val, w - MARGIN, y, { align: "right" });
    y += 16;
  });
  return y;
}

function footer(doc: jsPDF, business: string): void {
  const w = pageW(doc);
  const h = doc.internal.pageSize.getHeight();
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(MUTED);
    doc.text(`Generated by ${business} · ${dateShort(new Date())}`, MARGIN, h - 24);
    doc.text(`Page ${i} of ${pages}`, w - MARGIN, h - 24, { align: "right" });
  }
}

/* ------------------------------- builders ------------------------------- */

function buildInvoice(d: InvoicePdfData): Blob {
  const doc = newDoc();
  const start = header(
    doc,
    d.businessName,
    `Invoice #${d.invoiceNumber}`,
    d.referenceNumber ? `Ref ${d.referenceNumber}` : undefined,
  );
  const y = metaBlock(
    doc,
    [
      `Bill to: ${d.partyName}`,
      d.partyMeta,
      `Date: ${dateShort(d.dateISO)}    Channel: ${d.channel}    Status: ${d.status}`,
    ].filter(Boolean),
    start,
  );

  autoTable(doc, {
    ...tableOpts(),
    startY: y,
    head: [["Item", "Gross", "Net", "Glaze", "Rate", "Ctn", "Pkt", "Amount"]],
    body: d.lines.map((l) => [
      l.itemName,
      kg(l.grossKg),
      kg(l.netKg),
      `${l.glazingPct}%`,
      pkr(l.ratePerKg),
      l.cartonCount ?? "—",
      l.packetCount ?? "—",
      pkr(l.amount),
    ]),
    columnStyles: {
      1: { halign: "right" },
      2: { halign: "right" },
      3: { halign: "right" },
      4: { halign: "right" },
      5: { halign: "right" },
      6: { halign: "right" },
      7: { halign: "right" },
    },
  });

  let y2 = totals(
    doc,
    [
      ["Total", pkr(d.total)],
      ["Paid", pkr(d.paid)],
      ["Balance due", pkr(d.balance)],
    ],
    lastY(doc) + 16,
  );

  if (d.notes) {
    y2 += 6;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(MUTED);
    doc.text("Notes", MARGIN, y2);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9.5);
    doc.setTextColor(INK);
    doc.text(doc.splitTextToSize(d.notes, pageW(doc) - MARGIN * 2), MARGIN, y2 + 14);
  }

  footer(doc, d.businessName);
  return doc.output("blob");
}

function buildStatement(d: StatementPdfData): Blob {
  const doc = newDoc();
  const start = header(
    doc,
    d.businessName,
    "Account Statement",
    d.asOfISO ? `As of ${dateShort(d.asOfISO)}` : undefined,
  );
  const y = metaBlock(
    doc,
    [d.partyName, d.partyMeta, `Opening balance: ${pkr(d.opening)}`].filter(Boolean),
    start,
  );

  autoTable(doc, {
    ...tableOpts(),
    startY: y,
    head: [["Date", "Detail", "Debit", "Credit", "Balance"]],
    body: d.rows.map((r) => [
      dateShort(r.dateISO),
      `${r.kind}${r.ref ? " " + r.ref : ""}${r.meta ? " · " + r.meta : ""}`,
      r.debit ? pkr(r.debit) : "",
      r.credit ? pkr(r.credit) : "",
      pkr(r.balance),
    ]),
    columnStyles: { 2: { halign: "right" }, 3: { halign: "right" }, 4: { halign: "right" } },
  });

  totals(doc, [["Net outstanding", pkr(d.netOutstanding)]], lastY(doc) + 16);
  footer(doc, d.businessName);
  return doc.output("blob");
}

function weeklySection(doc: jsPDF, title: string, rows: WeeklyPdfRow[], startY: number): number {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(INK);
  doc.text(title, MARGIN, startY);
  autoTable(doc, {
    ...tableOpts(),
    startY: startY + 6,
    head: [["Party", "Detail", "Outstanding"]],
    body: rows.length
      ? rows.map((r) => [r.name, r.detail, pkr(r.outstanding)])
      : [["—", "No entries", ""]],
    columnStyles: { 2: { halign: "right" } },
  });
  return lastY(doc) + 20;
}

function buildWeekly(d: WeeklyPdfData): Blob {
  const doc = newDoc();
  let y = header(
    doc,
    d.businessName,
    "Weekly Statement",
    `${dateShort(d.fromISO)}  →  ${dateShort(d.toISO)}`,
  );
  y = weeklySection(doc, "Corporate receivables", d.corporate, y);
  y = weeklySection(doc, "Local receivables", d.local, y);
  y = weeklySection(doc, "Suppliers (payable)", d.suppliers, y);
  totals(
    doc,
    [
      ["Receivables", pkr(d.receivablesTotal)],
      ["Payables", pkr(d.payablesTotal)],
      ["Net position", pkr(d.net)],
    ],
    y,
  );
  footer(doc, d.businessName);
  return doc.output("blob");
}

function buildBadDebts(d: BadDebtsPdfData): Blob {
  const doc = newDoc();
  const start = header(doc, d.businessName, "Bad Debts & Disputes");
  autoTable(doc, {
    ...tableOpts(),
    startY: start,
    head: [["Date", "Party", "Invoice", "Type", "Amount", "Note"]],
    body: d.rows.map((r) => [
      dateShort(r.dateISO),
      r.name,
      r.invoiceNumber ? `#${r.invoiceNumber}` : "—",
      r.type,
      pkr(r.amount),
      r.note ?? "",
    ]),
    columnStyles: { 4: { halign: "right" } },
  });
  totals(
    doc,
    [
      ["Bad debts", pkr(d.badDebtTotal)],
      ["Disputes", pkr(d.disputeTotal)],
      ["Grand total", pkr(d.grandTotal)],
    ],
    lastY(doc) + 16,
  );
  footer(doc, d.businessName);
  return doc.output("blob");
}

export function buildPdf(kind: PdfKind, payload: PdfPayload): Blob {
  switch (kind) {
    case "invoice":
      return buildInvoice(payload as InvoicePdfData);
    case "statement":
      return buildStatement(payload as StatementPdfData);
    case "weekly":
      return buildWeekly(payload as WeeklyPdfData);
    case "badDebts":
      return buildBadDebts(payload as BadDebtsPdfData);
  }
}
